apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpc-proxy
  labels:
    app: rpc-proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rpc-proxy
  template:
    metadata:
      labels:
        app: rpc-proxy
    spec:
      containers:
        - name: rpc-proxy
          image: ethereumoptimism/rpc-proxy:0.4.1
          ports:
            - name: http
              containerPort: 8080
            - name: metrics
              containerPort: 9145
          env:
            - name: SEQUENCER
              value: sequencer:8545
            - name: RPC_METHODS_ALLOWED
              value: eth_blockNumber,eth_getBlockByNumber,eth_getBlockRange,eth_sendRawTransaction,eth_chainId,net_version,rollup_gasPrices
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            limits:
              memory: 256Mi
              cpu: "1"
            requests:
              memory: 128Mi
---
kind: Service
apiVersion: v1
metadata:
  name: rpc-proxy
  labels:
    app: rpc-proxy
spec:
  type: NodePort
  selector:
    app: rpc-proxy
  ports:
    - name: http
      protocol: TCP
      port: 8080
    - name: metrics
      protocol: TCP
      port: 9145
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rpc-proxy
spec:
  endpoints:
    - port: metrics
  selector:
    matchLabels:
      app: rpc-proxy
